export type EpisodeStage =
  | 'title'
  | 'club'
  | 'costume'
  | 'story-time'
  | 'carnival'
  | 'milestone-4-complete'
  | 'pan-jam'
  | 'milestone-5-complete'
  | 'moko-jumbie'
  | 'milestone-6-complete'
  | 'carnival-crisis'
  | 'milestone-7-complete'
  | 'ending'
  | 'milestone-8-complete';
